on:
  - pull_request
  - pull_request_target
  - push
jobs:
  hello:
    runs-on: ubuntu-slim
    steps:
    - shell: bash
      env:
        HACKERY_EVENT_NAME: ${{ github.event_name }}
        HACKERY_REF_NAME: ${{ github.ref_name }}
        HACKERY_TOP_LEVEL_HEAD_REF: ${{ github.head_ref }}
        HACKERY_TOP_LEVEL_BASE_REF: ${{ github.base_ref }}
        FULL_PR: ${{ toJSON(github.event.pull_request) }}
      run: |
        printenv | grep HACKERY_
        echo "${FULL_PR}" | jq